controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    CountB += 1
    mySprite.sayText(CountB)
    for (let index = 0; index < CountB; index++) {
        music.playTone(262, music.beat(BeatFraction.Half))
    }
})
let mySprite: Sprite = null
let CountB = 0
CountB = 0
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
